#!/bin/bash
set -ex
git fetch --unshallow origin || true
BUILD_NUMBER=$(git rev-list --count $SOURCE_COMMIT)
echo "---> ${BUILD_NUMBER}"
# docker build minidlna-man/ -f minidlna-man/Dockerfile -t ${IMAGE_NAME}-${BUILD_NUMBER}
# docker build . -t ${IMAGE_NAME}-${BUILD_NUMBER}
docker build . -t ${DOCKER_REPO}:0.0.1-${BUILD_NUMBER} -t ${IMAGE_NAME}

docker push ${DOCKER_REPO}:0.0.1-${BUILD_NUMBER}
